import os
import json
import uuid
import math
import re
import string
from datetime import datetime, timezone
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

# ── Rate Limiting ─────────────────────────────────────────────────────────────
# A typical human writer submits their own work occasionally — maybe a few times
# per hour at most. 10/minute prevents scripted flooding while still allowing
# burst testing. 100/day reflects a realistic upper bound for any single user.
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Audit Log (in-memory + persisted to audit_log.json) ──────────────────────
AUDIT_LOG_FILE = "audit_log.json"

def load_log():
    if os.path.exists(AUDIT_LOG_FILE):
        with open(AUDIT_LOG_FILE, "r") as f:
            return json.load(f)
    return []

def save_log(entries):
    with open(AUDIT_LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

def append_log(entry):
    entries = load_log()
    entries.append(entry)
    save_log(entries)

def get_log():
    return load_log()

def update_log_entry(content_id, updates):
    entries = load_log()
    for entry in entries:
        if entry.get("content_id") == content_id:
            entry.update(updates)
            save_log(entries)
            return entry
    return None

# ── Signal 1: LLM-Based Semantic Classifier (Groq) ───────────────────────────
def classify_with_llm(text: str) -> float:
    """
    Returns a float 0.0–1.0 where 1.0 = high confidence AI-generated.
    Uses Groq llama-3.3-70b-versatile with a structured prompt.
    """
    client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

    prompt = f"""You are an expert in distinguishing human-written text from AI-generated text.

Analyze the following piece of writing and return ONLY a JSON object with a single field "score".

The score should be a float between 0.0 and 1.0:
- 0.0 means you are highly confident this was written by a human
- 1.0 means you are highly confident this was generated by an AI

Look for signals such as:
- Unnaturally balanced or parallel sentence structures
- Overuse of discourse markers ("furthermore", "additionally", "it is important to note")
- Lack of personal voice, idiosyncratic phrasing, or emotional specificity
- Suspiciously uniform sentence length and rhythm
- Generic hedging language without concrete personal detail

Text to analyze:
\"\"\"
{text}
\"\"\"

Return ONLY valid JSON, no explanation, no markdown. Example: {{"score": 0.82}}"""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=50,
        )
        raw = response.choices[0].message.content.strip()
        # Strip any accidental markdown fences
        raw = raw.replace("```json", "").replace("```", "").strip()
        data = json.loads(raw)
        score = float(data.get("score", 0.5))
        return max(0.0, min(1.0, score))
    except Exception as e:
        app.logger.error(f"LLM signal error: {e}")
        return 0.5  # Return uncertain on failure


# ── Signal 2: Stylometric Heuristics (Pure Python) ───────────────────────────
def compute_stylometric_score(text: str) -> float:
    """
    Returns a float 0.0–1.0 where 1.0 = AI-like (uniform, low variance).

    Metrics:
    1. Sentence length variance — low variance → AI-like
    2. Type-token ratio (TTR) — low vocabulary diversity → AI-like
    3. Punctuation diversity — few distinctive marks → AI-like
    4. Average sentence length — very uniform mid-range → AI-like
    """
    # Tokenize sentences
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        # Too short to analyze reliably — return neutral
        return 0.5

    # Metric 1: Sentence length variance
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    # AI text has std_dev typically < 5; human writing tends > 8
    # Normalize: std_dev of 0 → score=1.0 (AI), std_dev of 15+ → score=0.0 (human)
    variance_score = max(0.0, 1.0 - (std_dev / 15.0))

    # Metric 2: Type-token ratio
    words = re.findall(r'\b\w+\b', text.lower())
    if len(words) == 0:
        ttr_score = 0.5
    else:
        unique_words = set(words)
        ttr = len(unique_words) / len(words)
        # AI text TTR often 0.5–0.7; human often 0.65–0.9
        # High TTR → human; low TTR → AI
        # Normalize: ttr of 0.4 → score=1.0 (AI), ttr of 0.85+ → score=0.0 (human)
        ttr_score = max(0.0, min(1.0, (0.85 - ttr) / 0.45))

    # Metric 3: Punctuation diversity (em-dashes, ellipses, exclamations, colons used naturally)
    distinctive_punct = len(re.findall(r'[—–…!?;:]', text))
    total_chars = len(text)
    punct_density = distinctive_punct / total_chars if total_chars > 0 else 0
    # High punctuation diversity → human; low → AI
    # 0 distinctive punct → score=1.0; density > 0.03 → score=0.0
    punct_score = max(0.0, 1.0 - (punct_density / 0.03))

    # Weighted combination of stylometric metrics
    style_score = (0.4 * variance_score) + (0.35 * ttr_score) + (0.25 * punct_score)
    return max(0.0, min(1.0, style_score))


# ── Confidence Scoring ────────────────────────────────────────────────────────
def combine_scores(llm_score: float, style_score: float) -> float:
    """
    Weighted combination: LLM (semantic) carries more weight because it captures
    holistic patterns that heuristics miss. Style provides a structural check.
    combined = 0.6 * llm_score + 0.4 * style_score
    """
    return round(0.6 * llm_score + 0.4 * style_score, 4)


def score_to_attribution(score: float) -> str:
    if score > 0.75:
        return "likely_ai"
    elif score < 0.35:
        return "likely_human"
    else:
        return "uncertain"


# ── Transparency Label Generator ─────────────────────────────────────────────
def generate_label(attribution: str, confidence: float) -> str:
    pct = round(confidence * 100)

    if attribution == "likely_ai":
        return (
            f"⚠️ AI-Generated Content Detected\n"
            f"Our system has analyzed this submission and found strong indicators that it was "
            f"generated by an AI writing tool rather than written by a human.\n"
            f"Confidence: {pct}% | Signals: Semantic patterns, Writing style analysis\n"
            f"This label does not block publishing. If you believe this is incorrect, "
            f"you can submit an appeal — our team will review your submission personally."
        )
    elif attribution == "likely_human":
        return (
            f"✅ Likely Human-Written\n"
            f"Our system analyzed this submission and found strong indicators of authentic "
            f"human authorship — varied sentence structure, natural voice, and organic style.\n"
            f"Confidence: {pct}% | Signals: Semantic patterns, Writing style analysis\n"
            f"AI detection is not perfect. This label reflects our best assessment, not a guarantee."
        )
    else:  # uncertain
        return (
            f"🔍 Authorship Uncertain\n"
            f"Our system could not confidently determine whether this content was written by "
            f"a human or generated by AI. It shows a mix of signals.\n"
            f"Confidence: {pct}% | Signals: Semantic patterns, Writing style analysis\n"
            f"This content will be displayed without an authorship badge. If you are the "
            f"human author, you can submit an appeal to have your work reviewed."
        )


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    """
    POST /submit
    Body: { "text": "...", "creator_id": "..." }
    Returns: content_id, attribution, confidence, label, signal scores
    """
    data = request.get_json(force=True, silent=True)
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request body must include 'text' and 'creator_id' fields."}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"].strip()

    if len(text) < 10:
        return jsonify({"error": "Text is too short to analyze (minimum 10 characters)."}), 400

    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    # Run both detection signals
    llm_score = classify_with_llm(text)
    style_score = compute_stylometric_score(text)

    # Combine into confidence score
    confidence = combine_scores(llm_score, style_score)
    attribution = score_to_attribution(confidence)
    label = generate_label(attribution, confidence)

    # Write structured audit log entry
    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": round(llm_score, 4),
        "style_score": round(style_score, 4),
        "status": "classified",
        "appeal_reasoning": None,
        "appeal_timestamp": None,
    }
    append_log(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": round(llm_score, 4),
        "style_score": round(style_score, 4),
        "label": label,
        "timestamp": timestamp,
    }), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    """
    POST /appeal
    Body: { "content_id": "...", "creator_reasoning": "..." }
    Updates status to "under_review" and logs the appeal.
    """
    data = request.get_json(force=True, silent=True)
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Request body must include 'content_id' and 'creator_reasoning'."}), 400

    content_id = data["content_id"].strip()
    reasoning = data["creator_reasoning"].strip()

    if not reasoning:
        return jsonify({"error": "creator_reasoning cannot be empty."}), 400

    appeal_timestamp = datetime.now(timezone.utc).isoformat()

    updated = update_log_entry(content_id, {
        "status": "under_review",
        "appeal_reasoning": reasoning,
        "appeal_timestamp": appeal_timestamp,
    })

    if updated is None:
        return jsonify({"error": f"No submission found with content_id '{content_id}'."}), 404

    return jsonify({
        "message": "Appeal received. Your submission has been flagged for human review.",
        "content_id": content_id,
        "status": "under_review",
        "appeal_timestamp": appeal_timestamp,
    }), 200


@app.route("/log", methods=["GET"])
def log():
    """
    GET /log
    Returns the most recent 50 audit log entries as JSON.
    In production this would require authentication — here it's for grading visibility.
    """
    entries = get_log()
    # Return most recent first
    return jsonify({"entries": list(reversed(entries[-50:]))})


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "service": "Provenance Guard"})


if __name__ == "__main__":
    app.run(debug=True, port=5000)
